### PR TITLE
Problem Solving 1 - 20

### PR DESCRIPTION
**Pull request by saadman-galib**

### CODE REVIEW

**Review by mdmarufsarker — APPROVED** [review]
No need to print put your input here.
Check the question

**Review by mdmarufsarker — APPROVED** [review]
Perfect

**Review by mdmarufsarker — APPROVED** [review]
Perfect

**Comment by saadman-galib** [comment]
> 

Ok

**Review by mdmarufsarker — APPROVED** [review]
Give some new line as it looks clearer to everyone about all the parts

**Review by mdmarufsarker — APPROVED** [review]

**Review by mdmarufsarker — APPROVED** [review]
Awesome technic for taking input from the user

**Review by mdmarufsarker — APPROVED** [review]
Ignore this type of variable name

**Comment by saadman-galib** [comment]
> Awesome technic for taking input from the user

Thanks

**Review by mdmarufsarker — APPROVED** [review]

**Comment by saadman-galib** [comment]
> Ignore this type of variable name

Ok

**Review by mdmarufsarker — APPROVED** [review]

**Review by mdmarufsarker — APPROVED** [review]

**Review by mdmarufsarker — APPROVED** [review]

**Review by mdmarufsarker — APPROVED** [review]

**Review by mdmarufsarker — APPROVED** [review]

**Review by mdmarufsarker — APPROVED** [review]

**Review by mdmarufsarker — APPROVED** [review]

**Review by mdmarufsarker — APPROVED** [review]

**Review by mdmarufsarker — APPROVED** [review]
Ignore this type of variable name

**Review by mdmarufsarker — APPROVED** [review]

**Pull request merged**
